// web/src/routes/init/media/+page.svelte
<script lang="ts">
  import { platform } from '$lib/stores/platform'
  import { i18n } from '$lib/i18n'
  import { z } from 'zod'
  import { validator } from '@felte/validator-zod'
  import { createForm } from 'felte'
  import { initConfig } from '$lib/stores/init'
  import { goto } from '$app/navigation'
  import RxInput from '$lib/components/RxInput.svelte'
  import RxForm from '$lib/components/RxForm.svelte'
  import RxFormItem from '$lib/components/RxFormItem.svelte'
  import RxButton from '$lib/components/RxButton.svelte'
  import RxCheckBox from '$lib/components/RxCheckBox.svelte'

  let schema = z.object({
    anti_theft: z.boolean(),
    limit: z.number().min(10, { message: $i18n.t('init.mediaLimitInvalid') }),
  })

  const { form, errors } = createForm({
    extend: validator({ schema }),
    onSubmit(values) {
      initConfig.update((data) => {
        data = {
          ...data,
          config: {
            media: values,
            ...data.config,
          },
        }
        return data
      })
      return Promise.resolve()
    },
    onSuccess() {
      goto('/init/pusher')
    },
  })
</script>

<svelte:head><title>{$i18n.t('init.mediaSettings')} - {$platform.name}</title></svelte:head>
<div class="flex-1 flex flex-row p-4 lg:p-6 justify-center">
  <div class="flex-1 flex flex-col max-w-5xl">
    <div class="m-2 md:m-4 flex flex-row justify-center items-center space-x-6">
      <span class="icon-[fluent--chevron-double-right-16-regular] opacity-60" />
      <h1 class="text-2xl font-bold">{$i18n.t('init.mediaSettings')}</h1>
      <span class="icon-[fluent--chevron-double-left-16-regular] opacity-60" />
    </div>
    <RxForm {form}>
      <RxFormItem
        name="limit"
        label={$i18n.t('init.mediaLimit')}
        hasError={$errors.limit !== null}
        errors={$errors.limit || ''}
      >
        <RxInput
          icon="icon-[fluent--code-16-regular]"
          class="w-full"
          id="limit"
          name="limit"
          hasError={$errors.limit !== null}
          placeholder={$i18n.t('init.mediaLimitPlaceholder')}
          value="25"
          type="number"
        />
      </RxFormItem>
      <RxFormItem name="anti_theft" label="" hasError={$errors.anti_theft !== null} errors={$errors.anti_theft || ''}>
        <RxCheckBox id="anti_theft" name="anti_theft" label={$i18n.t('init.mediaAntiTheft')} />
      </RxFormItem>
      <RxFormItem name="submitAction" label="">
        <RxButton class="w-full" level="primary" type="submit">{$i18n.t('init.next')}</RxButton>
      </RxFormItem>
    </RxForm>
  </div>
</div>

// web/src/routes/admin/media/index.tsx
import { usePlatformConfig, useUpdatePlatformConfigMutation } from "@api/platform";
import type { Config, MediaConfig } from "@models/config";
import { createForm, setValues } from "@modular-forms/solid";
import { Title } from "@storage/header";
import { t } from "@storage/theme";
import Button from "@widgets/button";
import Checkbox from "@widgets/checkbox";
import Input from "@widgets/input";
import Slider from "@widgets/slider";
import { createEffect } from "solid-js";

export default function () {
  const [form, { Form, Field }] = createForm<MediaConfig>();
  const config = usePlatformConfig();
  const mutation = useUpdatePlatformConfigMutation();
  createEffect(() => {
    if (config.data) {
      setValues(form, {
        path: config.data.media.path,
        limit: config.data.media.limit,
        anti_theft: config.data.media.anti_theft,
      });
    }
  });
  async function onSubmit(result: MediaConfig) {
    const mergedConfig = {
      ...config.data,
      media: result,
    } as Config;
    mutation.mutate(mergedConfig);
  }
  return (
    <>
      <Title page={t("media.title")} route="/admin/media" />
      <div class="flex-1 flex flex-col items-center p-3 lg:p-6">
        <Form onSubmit={onSubmit} class="w-full max-w-5xl flex flex-col space-y-2">
          <h3 class="h-12 flex items-center border-b border-b-layer-content/10 font-bold space-x-2">
            <span class="shrink-0 icon-[fluent--settings-20-regular] w-5 h-5" />
            <span>{t("media.title")}</span>
          </h3>
          <Field name="path">
            {(field, props) => (
              <Input
                class="flex-1"
                disabled
                title={t("media.form.path.label")}
                placeholder={t("media.form.path.placeholder")}
                icon={<span class="shrink-0 icon-[fluent--server-link-20-regular] w-5 h-5" />}
                value={field.value}
                error={field.error}
                {...props}
              />
            )}
          </Field>
          <div class="flex flex-col space-y-2 lg:flex-row lg:space-y-0 lg:space-x-2 lg:items-end">
            <Field name="anti_theft" type="boolean">
              {(field, props) => (
                <Checkbox
                  inputProps={props}
                  title={t("media.form.antiTheft.label")}
                  checked={field.value ?? false}
                  error={field.error}
                >
                  <span class="flex-1 text-start">{t("media.form.antiTheft.label")}</span>
                </Checkbox>
              )}
            </Field>
            <Field name="limit" type="number">
              {(field, props) => (
                <Slider
                  class="flex-1"
                  label={t("media.form.limit.label")}
                  max={1000}
                  min={10}
                  step={10}
                  name={field.name}
                  value={[field.value || 1]}
                  inputProps={props}
                  onValueChange={(e) => {
                    setValues(form, { [field.name]: e.value[0] });
                  }}
                />
              )}
            </Field>
          </div>
          <Button
            type="submit"
            level="primary"
            class="mt-4!"
            loading={config.isLoading || mutation.isPending}
            disabled={config.isLoading || mutation.isPending}
          >
            {t("general.actions.save.title")}
          </Button>
        </Form>
      </div>
    </>
  );
}
