// web/src/routes/account/login/index.tsx
import { useLoginMutation, useOAuthProviders } from "@api/account";
import LogoAnimate from "@assets/animates/logo-animate";
import Captcha from "@blocks/captcha";
import { mediaPath } from "@lib/utils/media";
import { createForm, minLength, pattern, required, setValue } from "@modular-forms/solid";
import { A, useLocation, useNavigate } from "@solidjs/router";
import { accountStore } from "@storage/account";
import { Title } from "@storage/header";
import { t } from "@storage/theme";
import { addToast } from "@storage/toast";
import Button from "@widgets/button";
import Card from "@widgets/card";
import Divider from "@widgets/divider";
import Input from "@widgets/input";
import Link from "@widgets/link";
import Popover from "@widgets/popover";
import { DateTime } from "luxon";
import { createSignal, For, Match, Switch } from "solid-js";

type LoginForm = {
  account: string;
  password: string;
  captcha_id: string;
  captcha_answer: string;
};

export default function () {
  const navigate = useNavigate();
  const location = useLocation();
  if (accountStore.token) {
    navigate("/", { replace: true });
    return null;
  }
  const [form, { Form, Field }] = createForm<LoginForm>();
  const oauthProviders = useOAuthProviders();

  const [timestamp, setTimestamp] = createSignal(DateTime.now().toMillis());

  const loginMutation = useLoginMutation({
    onSuccess: () => {
      addToast({
        level: "success",
        description: t("account.login.status.success.message"),
        duration: 5000,
        // img: xdsecMascotHappy,
      });
      const redirectUrl = location.query.redirect;
      if (redirectUrl) {
        const url = Array.isArray(redirectUrl) ? redirectUrl[0] : redirectUrl;
        if (/^(\w+):\/\//.test(url)) {
          navigate("/", { replace: true });
          window.location.replace(url);
        } else {
          navigate(url, { replace: true });
        }
      } else {
        navigate("/", { replace: true });
      }
    },
    onError: () => {
      setTimestamp(DateTime.now().toMillis());
      setValue(form, "password", "");
    },
  });
  function handleLogin(result: LoginForm) {
    loginMutation.mutate(result);
  }
  return (
    <>
      <Title page={t("account.login.title")} route="/account/login" />
      <div class="flex-1 flex flex-col items-center md:justify-center p-3 md:p-6">
        <Card
          class="w-full max-w-3xl"
          contentClass="p-6 flex flex-col md:flex-row space-y-2 space-x-0 md:space-x-6 md:space-y-0"
        >
          <Form onSubmit={handleLogin} class="md:w-0 flex-1 shrink-0 flex flex-col space-y-2">
            <h2 class="font-bold text-center">{t("account.login.title")}</h2>
            <Field
              name="account"
              validate={[
                required(t("account.form.account.required")),
                minLength(4, t("account.form.account.minimumLength")),
              ]}
            >
              {(field, props) => (
                <Input
                  icon={<span class="shrink-0 icon-[fluent--person-20-regular] w-5 h-5" />}
                  placeholder={t("account.form.account.placeholder")}
                  title={t("account.form.account.label")}
                  autocomplete="username"
                  {...props}
                  value={field.value}
                  error={field.error}
                  required
                  onFocusIn={() => {
                    // setMascot(xdsecMascotNormal);
                  }}
                  onFocusOut={() => {
                    // setMascot(null);
                  }}
                />
              )}
            </Field>
            <Field
              name="password"
              validate={[
                required(t("account.form.password.required")),
                minLength(8, t("account.form.password.minimumLength")),
                pattern(
                  // biome-ignore lint/correctness/noEmptyCharacterClassInRegex: password allows any characters
                  /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[^]{8,40}$/,
                  t("account.form.password.tooWeak")
                ),
              ]}
            >
              {(field, props) => (
                <Input
                  icon={<span class="shrink-0 icon-[fluent--lock-20-regular] w-5 h-5" />}
                  type="password"
                  placeholder={t("account.form.password.placeholder")}
                  title={t("account.form.password.label")}
                  extraLabel={
                    <A href="/account/forgot" class="hover:underline flex items-center space-x-1">
                      <span class="shrink-0 icon-[fluent--question-circle-16-regular] w-4 h-4 text-primary" />
                      <span>{t("account.forgot.title")}</span>
                    </A>
                  }
                  autocomplete="current-password"
                  {...props}
                  value={field.value}
                  error={field.error}
                  onFocusIn={() => {
                    // setMascot(xdsecMascotUnsee);
                  }}
                  onFocusOut={() => {
                    // setMascot(null);
                  }}
                />
              )}
            </Field>
            <Field name="captcha_id">
              {(idField) => (
                <Field
                  name="captcha_answer"
                  validate={[
                    required(t("captcha.form.answer.required")),
                    minLength(4, t("captcha.form.answer.minimumLength")),
                  ]}
                >
                  {(answerField, props) => (
                    <Captcha
                      {...props}
                      captchaForm={form}
                      idFieldValue={idField.value}
                      idFieldError={idField.error}
                      answerFieldValue={answerField.value}
                      answerFieldError={answerField.error}
                      timestamp={timestamp()}
                    />
                  )}
                </Field>
              )}
            </Field>
            <Button type="submit" level="primary" class="!mt-4" loading={loginMutation.isPending} disabled={loginMutation.isPending}>
              {t("account.login.title")}
            </Button>
          </Form>
          <Divider class="md:hidden" />
          <Divider class="hidden md:inline-block" direction="vertical" />
          <div class="md:w-0 flex-1 shrink-0 flex flex-col items-center space-y-2">
            <div class="flex-1 flex flex-col items-center justify-center">
              <LogoAnimate class="w-36 h-36 hidden md:inline-block my-6" />
            </div>
            <Link class="w-full" href="/account/register">
              {t("account.register.tips")}
            </Link>
            <Switch>
              <Match when={oauthProviders.data?.filter((s) => s.portal).length === 1}>
                {(() => {
                  const svc = oauthProviders.data?.find((s) => s.portal)!;
                  return (
                    <Link class="w-full !mt-4" href={svc.portal} title={svc.name}>
                      <img src={mediaPath(svc.avatar ?? "")} alt={svc.name} width={24} height={24} />
                      <span>{svc.name}</span>
                    </Link>
                  );
                })()}
              </Match>
              <Match when={oauthProviders.data && oauthProviders.data.filter((s) => s.portal).length > 1}>
                <Popover
                  class="w-full !mt-4"
                  btnContent={
                    <>
                      <span class="shrink-0 icon-[fluent--person-passkey-20-regular] w-5 h-5" />
                      <span>{t("account.oauth.select")}</span>
                    </>
                  }
                >
                  <Card contentClass="p-2 flex flex-col space-y-2">
                    <For each={oauthProviders.data?.filter((s) => s.portal)}>
                      {(service) => (
                        <Link class="w-full" justify="start" size="sm" href={service.portal} title={service.name} ghost>
                          <img src={mediaPath(service.avatar ?? "")} alt={service.name} width={24} height={24} />
                          <span>{service.name}</span>
                        </Link>
                      )}
                    </For>
                  </Card>
                </Popover>
              </Match>
            </Switch>
          </div>
        </Card>
      </div>
    </>
  );
}

// web/src/routes/account/login/+page.svelte
<script lang="ts">
  import RxButton from '$lib/components/RxButton.svelte'
  import RxCard from '$lib/components/RxCard.svelte'
  import RxForm from '$lib/components/RxForm.svelte'
  import RxFormItem from '$lib/components/RxFormItem.svelte'
  import RxInput from '$lib/components/RxInput.svelte'
  import Logo from '$lib/assets/logo.svg'
  import { platform } from '$lib/stores/platform'
  import { i18n } from '$lib/i18n'
  import { z } from 'zod'
  import { validator } from '@felte/validator-zod'
  import { createForm } from 'felte'
  import Captcha from '$lib/blocks/Captcha.svelte'
  import RxLink from '$lib/components/RxLink.svelte'
  import { login } from '$lib/api/account'
  import { goto } from '$app/navigation'
  import { showMessage } from '$lib/stores/toast'
  import type { AxiosError } from 'axios'
  import { page } from '$app/stores'

  let schema = z.object({
    account: z
      .string()
      .trim()
      .min(2, { message: $i18n.t('account.accountTooShort') })
      .max(32, { message: $i18n.t('account.accountTooLong') }),
    password: z
      .string()
      .trim()
      .min(8, { message: $i18n.t('account.passwordTooShort') })
      .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[^]{8,40}$/, { message: $i18n.t('account.passwordTooWeak') }),
    captcha_id: z.string().trim(),
    captcha_answer: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('account.captchaIsRequired') }),
  })
  let loading = false
  let captcha: Captcha | null
  const { form, data, touched, errors } = createForm({
    extend: validator({ schema }),
    onSubmit(values) {
      loading = true
      return login({ ...values })
    },
    onSuccess() {
      loading = false
      showMessage('success', $i18n.t('account.loginSuccess'), 5000)
      goto($page.url.searchParams.get('redirect') || '/')
    },
    onError(error) {
      loading = false
      showMessage('error', $i18n.t('account.loginFailed') + ': ' + (error as AxiosError).response?.data, 5000)
      captcha?.refreshAll()
    },
  })

  const captchaAnswerValue = $data.captcha_answer
  $: {
    // console.log('answer', captchaAnswerValue, $data.captcha_answer)
    if (captchaAnswerValue !== $data.captcha_answer) {
      $touched.captcha_answer = true
    }
  }

  const captchaIdValue = $data.captcha_id
  $: {
    // console.log('id', captchaIdValue, $data.captcha_id)
    if (captchaIdValue !== $data.captcha_id) {
      $touched.captcha_id = true
    }
  }
</script>

<svelte:head><title>{$i18n.t('account.login')} - {$platform.name}</title></svelte:head>

<div class="flex-1 flex flex-col md:justify-center items-center p-3 lg:p-6">
  <RxCard class="flex flex-col md:flex-row w-full max-w-4xl">
    <div class="md:w-0 flex-1 flex-col">
      <h1 class="text-center font-bold text-base">{$i18n.t('account.login')}</h1>
      <RxForm {form}>
        <RxFormItem
          name="account"
          label={$i18n.t('account.account')}
          hasError={$errors.account !== null}
          errors={$errors.account || ''}
        >
          <RxInput
            icon="icon-[fluent--person-16-regular]"
            class="w-full"
            id="account"
            name="account"
            hasError={$errors.account !== null}
            autocomplete="username"
          />
        </RxFormItem>
        <RxFormItem name="password" label="" hasError={$errors.password !== null} errors={$errors.password || ''}>
          <span slot="label" class="text-sm font-bold opacity-60 flex flex-row justify-between w-full">
            <span>{$i18n.t('account.password')}</span>
            <a class="hover:underline" href="/account/forgot-password">{$i18n.t('account.forgotPassword')}</a>
          </span>
          <RxInput
            icon="icon-[fluent--lock-16-regular]"
            class="w-full"
            id="password"
            type="password"
            name="password"
            hasError={$errors.password !== null}
            autocomplete="current-password"
          />
        </RxFormItem>
        <Captcha
          bind:this={captcha}
          hasError={$errors.captcha_answer !== null}
          errors={$errors.captcha_answer || ''}
          bind:captchaId={$data.captcha_id}
          bind:captchaAnswer={$data.captcha_answer}
        />
        <RxFormItem name="submitAction" label="">
          <RxButton class="w-full" level="primary" type="submit" {loading}>{$i18n.t('account.login')}</RxButton>
        </RxFormItem>
      </RxForm>
    </div>
    <div class="divider md:divider-horizontal opacity-60">{$i18n.t('misc.or')}</div>
    <div class="md:w-0 flex-1 flex flex-col space-y-6">
      <div class="flex-1 md:flex flex-col justify-center items-center hidden">
        <img class="object-fit max-h-48" src={Logo} alt="Ret2Shell" />
      </div>
      <RxLink class="w-full" href="/account/register">{$i18n.t('account.registerTips')}</RxLink>
      <RxLink class="w-full" href="/account/oauth">{$i18n.t('account.3rdAuth')}</RxLink>
    </div>
  </RxCard>
</div>
